name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKERHUB_REPO: adityagupta1903/onlinejudge  # Replace with your Docker Hub repository
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      EC2_USERNAME: ubuntu  # Adjust if your EC2 instance uses a different username
      EC2_HOST: ec2-16-171-151-38.eu-north-1.compute.amazonaws.com  # Replace with your EC2 instance's public DNS or IP

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - name: Build and Push Docker image
         uses: docker/build-push-action@v2
         with:
           context: .
           file: ./Dockerfile
           push: true
           tags: adityagupta1903/onlinejudge:latest

      - name: Verify Pushed Image
           run: docker pull adityagupta1903/onlinejudge:latest

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull adityagupta1903/onlinejudge:latest
            sudo docker docker pull redis
            sudo docker stop onlinejudge || true
            sudo docker rm  onlinejudge || true
            sudo docker stop my-redis-container || true
            sudo docker rm my-redis-container onlinejudge || true
            docker run -d --name my-redis-container -p 6379:6379 redis
            sudo docker run -d --name onlinejudge -p 3000:3000 --link my-redis-container:redis -e REDIS_HOST=redis adityagupta1903/onlinejudge:latest
